name: mi_segunda_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Animaciones y efectos visuales
  animate_do: ^4.2.0
  shimmer: ^3.0.0
  lottie: ^3.1.0

  # Gráficos y visualización
  fl_chart: ^1.1.1
  percent_indicator: ^4.2.3

  # UI mejorada
  glassmorphism: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.2.1

  # Para análisis de voz
  record: ^6.1.2
  path_provider: ^2.1.0
  permission_handler: ^12.0.1
  audioplayers: ^6.5.1

  sensors_plus: ^4.0.2
  pedometer: ^4.0.1

  # Base de datos
  sqflite: ^2.3.0
  path: ^1.8.3

  # HTTP para peticiones a la API
  http: ^1.6.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logoNV1.jpeg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logoNV1.jpeg"

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/